### ISSUE TITLE
关于yolov5数据转化问题

### ISSUE THREAD

**Issue by ASguoyue** [onehahaha756/yolov5_rotation#14]
## ❔Question
yolov5中的数据格式为x y w h 使用cv.minAreaRect代码转换后，会导致一部分的w h的大小进行调换，请问有这种情况吗？我也看来那个函数的用法了，在旋转的时候都是默认第一条边为w

**Comment by onehahaha756** [comment]
代码里面默认第一条边为w，在图像长宽一致的时候，代码没啥问题的。图像长宽不一致的时候，转化的时候会出问题。

**Comment by ASguoyue** [comment]
> 代码里面默认第一条边为w，在图像长宽一致的时候，代码没啥问题的。图像长宽不一致的时候，转化的时候会出问题。

好类，那这个我在看看，能不能修改一下

**Comment by onehahaha756** [comment]
可以参考lastest分支，data/hrsc20162rotation.py那个代码。改了那个之后，dataset加载和标签可视化那里都需要相应的改一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ASguoyue ***@***.***&gt;
发送时间: 2021年12月30日 11:06
收件人: onehahaha756/yolov5_rotation ***@***.***&gt;
抄送: onehahaha756 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [onehahaha756/yolov5_rotation] 关于yolov5数据转化问题 (Issue #14)

**Comment by ASguoyue** [comment]
> 好的，我看一下，谢谢老哥

**Comment by ASguoyue** [comment]
> 可以参考lastest分支，data/hrsc20162rotation.py那个代码。改了那个之后，dataset加载和标签可视化那里都需要相应的改一下。

老哥你好，请问一下你的这个旋转框角度回归的，是使用了csl的模型吗？

**Comment by onehahaha756** [comment]
没有，比较简单粗暴，直接输出角度。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ASguoyue ***@***.***&gt;
发送时间: 2022年1月4日 23:15
收件人: onehahaha756/yolov5_rotation ***@***.***&gt;
抄送: onehahaha756 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [onehahaha756/yolov5_rotation] 关于yolov5数据转化问题 (Issue #14)





  
可以参考lastest分支，data/hrsc20162rotation.py那个代码。改了那个之后，dataset加载和标签可视化那里都需要相应的改一下。
  
老哥你好，请问一下你的这个旋转框角度回归的，是使用了csl的模型吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
