### ISSUE TITLE
关于utils/cut2rotation.py脚本的问题

### ISSUE THREAD

**Issue by stevenXS** [onehahaha756/yolov5_rotation#2]
## ❔Question
作者您好，cut2rotation.py中有一句：“from dota2rotation import *”，请问dota2rotation 该脚本是不需要吗！

**Comment by onehahaha756** [comment]
嗨，您好，刚确认了一下是不需要的，因为我把dota2rotation脚本里的函数都拷进来了。

**Comment by stevenXS** [comment]
谢谢！
