### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.general'

### ISSUE THREAD

**Issue by Yilangshuo** [onehahaha756/yolov5_rotation#6]
请问你的程序是不是要再utils文件夹下加入utils.py文件才行？

**Comment by onehahaha756** [comment]
应该是，报错的话，可能需要改一下开头的import

**Comment by Yilangshuo** [comment]
你好，感谢你的回信。这个问题我之前解决了，重新配置了环境，安装了web.py这个模块就好了，后来成功运行，但却总是发散的。调整了batch-size后都不好使，我也用了你说的anchor程序，用自己的数据得出了新的anchor，但都是发散的。batchsize我是用的16，就按照你说的。但为什么label那一项总是5，并且除准确率P会出现较高值外其他的像召回率R、mAp等都非常低。
如果方便的话，还请你为我解答一下。




---Original---
From: ***@***.***&gt;
Date: Mon, Nov 8, 2021 09:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [onehahaha756/yolov5_rotation] ModuleNotFoundError: No modulenamed 'utils.general' (Issue #6)




 
应该是，报错的话，可能需要改一下开头的import
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by onehahaha756** [comment]
你说训练过程中label那一项吗？方便的话可以给我截个图看看。

**Comment by Yilangshuo** [comment]
见图片附件

---Original---
From: ***@***.***&gt;
Date: Mon, Nov 15, 2021 18:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [onehahaha756/yolov5_rotation] ModuleNotFoundError: No modulenamed 'utils.general' (Issue #6)




 
你说训练过程中label那一项吗？方便的话可以给我截个图看看。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Yilangshuo** [comment]
非常感谢你的回复，希望没打扰你的研究工作。



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 15, 2021 18:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [onehahaha756/yolov5_rotation] ModuleNotFoundError: No modulenamed 'utils.general' (Issue #6)




 
你说训练过程中label那一项吗？方便的话可以给我截个图看看。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by onehahaha756** [comment]
嗨，我不知道github评论能不能传图片哈，那个你发的我没看到。

**Comment by Yilangshuo** [comment]
感谢你的回信。你是说我刚才几次通过QQ邮件发的图片你都收不到吗？github上我没试过，我等会去看看



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 15, 2021 18:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [onehahaha756/yolov5_rotation] ModuleNotFoundError: No module named 'utils.general' (Issue #6)




 
嗨，我不知道github评论能不能传图片哈，那个你发的我没看到。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Yilangshuo** [comment]
![13_g](https://user-images.githubusercontent.com/93815123/141770598-bb46965d-c9be-431d-a272-53dac10f6578.png)

**Comment by onehahaha756** [comment]
label那个应该保存的是最后一个batch中目标的数量，至于召回率为什么这么低。我也看不出来。

**Comment by Yilangshuo** [comment]
好的，再次感谢你的回信，我之后再好好看看

**Comment by Lina9293** [comment]
> 

hi，请问你这个问题有解决吗？我也碰到了这个问题，暂时还没有排查出来

**Comment by Lina9293** [comment]
> 好的，再次感谢你的回信，我之后再好好看看

hi，请问你这个问题找到原因了吗？我也碰到这个问题了，暂时还没有排查出来。也是p值很高，其他都很低。
